/**
 * Unit tests for caddyfile.ts — generator and validation.
 *
 * Run with: npx tsx apps/web/lib/caddyfile.test.ts
 * (tsx is available via npx, no install needed)
 */

import assert from 'node:assert/strict';
import {
  generateSiteBlock,
  validateServiceInput,
  availableTlsModes,
  getDefaultTlsMode,
  validateTlsModeConfigured,
  ValidationError,
  type CaddyfileService,
  type TlsMode,
} from './caddyfile';

let passed = 0;
let failed = 0;

function test(name: string, fn: () => void) {
  try {
    fn();
    passed++;
    console.log(`  ✓ ${name}`);
  } catch (err: unknown) {
    failed++;
    console.error(`  ✗ ${name}`);
    console.error(`    ${err instanceof Error ? err.message : String(err)}`);
  }
}

function proxyService(overrides: Partial<CaddyfileService> = {}): CaddyfileService {
  return {
    id: 'cmabc123',
    domains: ['piren.org', 'www.piren.org'],
    upstreamContainer: 'piren_app',
    upstreamPort: 3000,
    tlsMode: 'acme' as TlsMode,
    serviceType: 'proxy',
    staticRoot: null,
    ...overrides,
  };
}

function staticService(overrides: Partial<CaddyfileService> = {}): CaddyfileService {
  return {
    id: 'cmxyz789',
    domains: ['landing.staging.lucchesi.io'],
    upstreamContainer: null,
    upstreamPort: null,
    tlsMode: 'namecheap_tls' as TlsMode,
    serviceType: 'static',
    staticRoot: '/srv/sites/landing.staging.lucchesi.io',
    ...overrides,
  };
}

// ── Proxy block generation ──────────────────────────────────────

console.log('\n# Proxy block generation');

test('generates valid proxy block', () => {
  const svc = proxyService();
  const output = generateSiteBlock(svc);
  assert.ok(output.includes('# Generated by Portcullis. Do not edit manually.'));
  assert.ok(output.includes('# Service ID: cmabc123'));
  assert.ok(output.includes('# Domains: piren.org, www.piren.org'));
  assert.ok(output.includes('piren.org www.piren.org {'));
  assert.ok(output.includes('  import acme'));
  assert.ok(output.includes('  reverse_proxy piren_app:3000'));
  assert.ok(output.includes('}'));
});

test('proxy block uses correct TLS import', () => {
  const svc = proxyService({ tlsMode: 'namecheap_tls' });
  const output = generateSiteBlock(svc);
  assert.ok(output.includes('  import namecheap_tls'));
});

test('proxy block with internal TLS', () => {
  const svc = proxyService({ tlsMode: 'internal' });
  const output = generateSiteBlock(svc);
  assert.ok(output.includes('  import internal'));
});

test('proxy block with cloudflare TLS', () => {
  const svc = proxyService({ tlsMode: 'cloudflare_tls' });
  const output = generateSiteBlock(svc);
  assert.ok(output.includes('  import cloudflare_tls'));
});

test('proxy block with route53 TLS', () => {
  const svc = proxyService({ tlsMode: 'route53_tls' });
  const output = generateSiteBlock(svc);
  assert.ok(output.includes('  import route53_tls'));
});

test('proxy block single domain', () => {
  const svc = proxyService({ domains: ['app.piren.org'] });
  const output = generateSiteBlock(svc);
  assert.ok(output.includes('app.piren.org {'));
  assert.ok(output.includes('  reverse_proxy piren_app:3000'));
});

// ── Static block generation ─────────────────────────────────────

console.log('\n# Static block generation');

test('generates valid static block', () => {
  const svc = staticService();
  const output = generateSiteBlock(svc);
  assert.ok(output.includes('# Generated by Portcullis. Do not edit manually.'));
  assert.ok(output.includes('# Service ID: cmxyz789'));
  assert.ok(output.includes('# Domains: landing.staging.lucchesi.io'));
  assert.ok(output.includes('landing.staging.lucchesi.io {'));
  assert.ok(output.includes('  import namecheap_tls'));
  assert.ok(output.includes('  root * /srv/sites/landing.staging.lucchesi.io'));
  assert.ok(output.includes('  file_server'));
  assert.ok(output.includes('}'));
});

test('static block uses acme TLS', () => {
  const svc = staticService({ tlsMode: 'acme' });
  const output = generateSiteBlock(svc);
  assert.ok(output.includes('  import acme'));
});

// ── Validation: invalid input rejection ─────────────────────────

console.log('\n# Input validation');

test('rejects invalid TLS mode', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ tlsMode: 'invalid' as TlsMode })),
    ValidationError
  );
});

test('rejects invalid hostname', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ domains: ['not a domain'] })),
    ValidationError
  );
});

test('rejects hostname with spaces', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ domains: ['bad domain.com'] })),
    ValidationError
  );
});

test('rejects empty domains', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ domains: [] })),
    ValidationError
  );
});

test('rejects proxy without upstream container', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ upstreamContainer: null })),
    ValidationError
  );
});

test('rejects proxy with invalid container name', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ upstreamContainer: 'my app!' })),
    ValidationError
  );
});

test('rejects proxy without upstream port', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ upstreamPort: null })),
    ValidationError
  );
});

test('rejects proxy with port 0', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ upstreamPort: 0 })),
    ValidationError
  );
});

test('rejects proxy with port > 65535', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ upstreamPort: 70000 })),
    ValidationError
  );
});

test('rejects static without staticRoot', () => {
  assert.throws(
    () => validateServiceInput(staticService({ staticRoot: null })),
    ValidationError
  );
});

test('rejects static with root outside /srv/sites/', () => {
  assert.throws(
    () => validateServiceInput(staticService({ staticRoot: '/var/www/site' })),
    ValidationError
  );
});

test('rejects static root with braces', () => {
  assert.throws(
    () => validateServiceInput(staticService({ staticRoot: '/srv/sites/{bad}' })),
    ValidationError
  );
});

test('rejects invalid service type', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ serviceType: 'invalid' as unknown as 'proxy' })),
    ValidationError
  );
});

// ── Validation: valid input acceptance ──────────────────────────

console.log('\n# Input acceptance');

test('accepts valid proxy service', () => {
  validateServiceInput(proxyService());
  // No throw = pass
});

test('accepts valid static service', () => {
  validateServiceInput(staticService());
});

test('accepts wildcard domain', () => {
  validateServiceInput(proxyService({ domains: ['*.staging.lucchesi.io'] }));
});

test('accepts multi-label domain', () => {
  validateServiceInput(proxyService({ domains: ['api.indienexus.staging.lucchesi.io'] }));
});

test('accepts container name with hyphens and dots', () => {
  validateServiceInput(proxyService({ upstreamContainer: 'my-app_1.prod' }));
});

test('accepts normal cuid-like service ID', () => {
  validateServiceInput(proxyService({ id: 'cmabc123' }));
});

// ── Validation: service ID path traversal rejection ─────────────

console.log('\n# Service ID path traversal rejection');

test('rejects service ID with path traversal ../manual/pwn', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ id: '../manual/pwn' })),
    ValidationError
  );
});

test('rejects service ID with subdir foo/bar', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ id: 'foo/bar' })),
    ValidationError
  );
});

test('rejects service ID that is just ..', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ id: '..' })),
    ValidationError
  );
});

test('rejects service ID with dotted extension foo.caddy/evil', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ id: 'foo.caddy/evil' })),
    ValidationError
  );
});

test('rejects service ID with leading dot', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ id: '.hidden' })),
    ValidationError
  );
});

test('rejects service ID with null byte', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ id: 'ok\x00bad' })),
    ValidationError
  );
});

// ── Generated filename uses service ID ──────────────────────────

console.log('\n# Filename');

test('filename uses service ID in generated block comments', () => {
  const svc = proxyService({ id: 'proj_cm123456' });
  const output = generateSiteBlock(svc);
  assert.ok(output.includes('# Service ID: proj_cm123456'));
});

// ── Edge cases ──────────────────────────────────────────────────

console.log('\n# Edge cases');

test('rejects domain with newline injection', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ domains: ['good.com\nbad.com'] })),
    ValidationError
  );
});

test('rejects container name with semicolons', () => {
  assert.throws(
    () => validateServiceInput(proxyService({ upstreamContainer: 'app;rm -rf /' })),
    ValidationError
  );
});

test('rejects static root with newline', () => {
  assert.throws(
    () => validateServiceInput(staticService({ staticRoot: '/srv/sites/ok\nbad' })),
    ValidationError
  );
});

// ── TLS mode availability detection (P2) ─────────────────────────

console.log('\n# TLS mode availability detection');

test('availableTlsModes includes acme and internal always', () => {
  const modes = availableTlsModes();
  const acme = modes.find(m => m.value === 'acme');
  const internal = modes.find(m => m.value === 'internal');
  assert.ok(acme, 'acme should be present');
  assert.ok(internal, 'internal should be present');
  assert.equal(acme!.available, true, 'acme should always be available');
  assert.equal(internal!.available, true, 'internal should always be available');
});

test('availableTlsModes: namecheap available when env vars set', () => {
  const prevKey = process.env.NAMECHEAP_API_KEY;
  const prevUser = process.env.NAMECHEAP_API_USER;
  process.env.NAMECHEAP_API_KEY = 'test-key';
  process.env.NAMECHEAP_API_USER = 'test-user';
  try {
    const mode = availableTlsModes().find(m => m.value === 'namecheap_tls')!;
    assert.ok(mode);
    assert.equal(mode.available, true);
  } finally {
    process.env.NAMECHEAP_API_KEY = prevKey;
    process.env.NAMECHEAP_API_USER = prevUser;
  }
});

test('availableTlsModes: namecheap unavailable when env vars not set', () => {
  // Ensure env vars are not set
  const prevKey = process.env.NAMECHEAP_API_KEY;
  const prevUser = process.env.NAMECHEAP_API_USER;
  delete process.env.NAMECHEAP_API_KEY;
  delete process.env.NAMECHEAP_API_USER;
  try {
    const mode = availableTlsModes().find(m => m.value === 'namecheap_tls')!;
    assert.equal(mode.available, false);
  } finally {
    if (prevKey !== undefined) process.env.NAMECHEAP_API_KEY = prevKey;
    if (prevUser !== undefined) process.env.NAMECHEAP_API_USER = prevUser;
  }
});

test('availableTlsModes: cloudflare available when token set', () => {
  const prev = process.env.CLOUDFLARE_API_TOKEN;
  process.env.CLOUDFLARE_API_TOKEN = 'test-cf-token';
  try {
    const mode = availableTlsModes().find(m => m.value === 'cloudflare_tls')!;
    assert.ok(mode);
    assert.equal(mode.available, true);
  } finally {
    process.env.CLOUDFLARE_API_TOKEN = prev;
  }
});

test('availableTlsModes: cloudflare unavailable when no token', () => {
  const prev = process.env.CLOUDFLARE_API_TOKEN;
  delete process.env.CLOUDFLARE_API_TOKEN;
  try {
    const mode = availableTlsModes().find(m => m.value === 'cloudflare_tls')!;
    assert.equal(mode.available, false);
  } finally {
    if (prev !== undefined) process.env.CLOUDFLARE_API_TOKEN = prev;
  }
});

test('availableTlsModes: route53 available when CADDY_DNS_PROVIDER is route53', () => {
  const prev = process.env.CADDY_DNS_PROVIDER;
  process.env.CADDY_DNS_PROVIDER = 'route53';
  try {
    const mode = availableTlsModes().find(m => m.value === 'route53_tls')!;
    assert.ok(mode);
    assert.equal(mode.available, true);
  } finally {
    process.env.CADDY_DNS_PROVIDER = prev;
  }
});

test('availableTlsModes: route53 unavailable without CADDY_DNS_PROVIDER', () => {
  const prev = process.env.CADDY_DNS_PROVIDER;
  delete process.env.CADDY_DNS_PROVIDER;
  try {
    const mode = availableTlsModes().find(m => m.value === 'route53_tls')!;
    assert.equal(mode.available, false);
  } finally {
    if (prev !== undefined) process.env.CADDY_DNS_PROVIDER = prev;
  }
});

// ── validateTlsModeConfigured ─────────────────────────────────────

console.log('\n# TLS mode validation');

test('validateTlsModeConfigured rejects invalid mode name', () => {
  const result = validateTlsModeConfigured('fake_mode');
  assert.ok(result !== null, 'should return an error message');
  assert.ok(result!.includes('Invalid'), 'error should mention Invalid');
});

test('validateTlsModeConfigured accepts acme (always available)', () => {
  const result = validateTlsModeConfigured('acme');
  assert.equal(result, null, 'acme should be valid');
});

test('validateTlsModeConfigured accepts internal (always available)', () => {
  const result = validateTlsModeConfigured('internal');
  assert.equal(result, null, 'internal should be valid');
});

test('validateTlsModeConfigured rejects mode that would be injected', () => {
  const result = validateTlsModeConfigured('malicious{#');
  assert.ok(result !== null);
  assert.ok(result!.includes('Invalid'));
});

// ── Default TLS mode selection ───────────────────────────────────

console.log('\n# Default TLS mode');

test('getDefaultTlsMode favors namecheap over acme when both available', () => {
  const prevKey = process.env.NAMECHEAP_API_KEY;
  const prevUser = process.env.NAMECHEAP_API_USER;
  process.env.NAMECHEAP_API_KEY = 'test';
  process.env.NAMECHEAP_API_USER = 'test';
  try {
    const mode = getDefaultTlsMode();
    assert.equal(mode, 'namecheap_tls');
  } finally {
    process.env.NAMECHEAP_API_KEY = prevKey;
    process.env.NAMECHEAP_API_USER = prevUser;
  }
});

// ── Summary ─────────────────────────────────────────────────────

console.log(`\n${'─'.repeat(40)}`);
console.log(`Results: ${passed} passed, ${failed} failed, ${passed + failed} total\n`);

process.exit(failed > 0 ? 1 : 0);
