-- Portcullis service registry (Slice 2).
-- Fresh schema per ADR-0001: this migration starts from an empty
-- database and no legacy-schema compatibility is retained.

CREATE TABLE services (
    -- Opaque, immutable service identifier (generated by the application,
    -- never derived from user input). Used as the generated Caddyfile name.
    id              TEXT PRIMARY KEY,
    service_type    TEXT NOT NULL CHECK (service_type IN ('proxy', 'static')),
    domains         TEXT[] NOT NULL CHECK (cardinality(domains) >= 1),
    tls_mode        TEXT NOT NULL
                    CHECK (tls_mode IN ('acme', 'internal', 'namecheap_tls', 'cloudflare_tls', 'route53_tls')),
    -- Proxy services only.
    proxy_container TEXT,
    proxy_port      INTEGER CHECK (proxy_port BETWEEN 1 AND 65535),
    -- Static services only. Must stay inside the /srv/sites/ boundary
    -- (application-enforced; re-checked in the Go core).
    static_root     TEXT,
    -- Optional per-service database identifiers (no credentials stored).
    db_name         TEXT,
    db_user         TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Type-discriminant integrity: proxy services need an upstream target
    -- and no static root; static services need a static root and no
    -- upstream target.
    CHECK (
        (service_type = 'proxy'
            AND proxy_container IS NOT NULL
            AND proxy_port IS NOT NULL
            AND static_root IS NULL)
        OR
        (service_type = 'static'
            AND static_root IS NOT NULL
            AND proxy_container IS NULL
            AND proxy_port IS NULL)
    )
);
