package registry

import (
	"fmt"
	"strings"
)

// GenerateSiteBlock renders the deterministic Caddy site block for a
// validated service. The service ID doubles as the generated filename;
// all domains appear in the site label, the TLS mode is imported as a
// snippet, and the body is a reverse_proxy (proxy) or root+file_server
// (static) directive. Generation is a pure function: identical input
// yields byte-identical output.
func GenerateSiteBlock(s Service) (string, error) {
	if err := s.Validate(); err != nil {
		return "", fmt.Errorf("registry: refusing to generate for invalid service: %w", err)
	}

	var lines []string
	lines = append(lines,
		"# Generated by Portcullis. Do not edit manually.",
		fmt.Sprintf("# Service ID: %s", s.ID),
		fmt.Sprintf("# Domains: %s", strings.Join(s.Domains, ", ")),
		"",
	)
	lines = append(lines,
		fmt.Sprintf("%s {", strings.Join(s.Domains, " ")),
		fmt.Sprintf("  import %s", string(s.TLSMode)),
	)
	switch s.Type {
	case TypeProxy:
		lines = append(lines, fmt.Sprintf("  reverse_proxy %s:%d", s.ProxyContainer, s.ProxyPort))
	case TypeStatic:
		lines = append(lines,
			fmt.Sprintf("  root * %s", s.StaticRoot),
			"  file_server",
		)
	}
	lines = append(lines, "}", "")
	return strings.Join(lines, "\n"), nil
}
