package registry

import (
	"strings"
	"testing"
	"time"
)

func proxyService() Service {
	return Service{
		ID:             "svc-alpha",
		Type:           TypeProxy,
		Domains:        []string{"app.example.com", "alt.example.com"},
		TLSMode:        TLSACME,
		ProxyContainer: "app_container",
		ProxyPort:      3000,
		CreatedAt:      time.Date(2026, 8, 27, 12, 0, 0, 0, time.UTC),
	}
}

func TestGenerateProxyBlock(t *testing.T) {
	got, err := GenerateSiteBlock(proxyService())
	if err != nil {
		t.Fatalf("GenerateSiteBlock: %v", err)
	}
	want := `# Generated by Portcullis. Do not edit manually.
# Service ID: svc-alpha
# Domains: app.example.com, alt.example.com

app.example.com alt.example.com {
  import acme
  reverse_proxy app_container:3000
}
`
	if got != want {
		t.Errorf("proxy block mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestGenerateStaticBlock(t *testing.T) {
	s := Service{
		ID:         "site-beta",
		Type:       TypeStatic,
		Domains:    []string{"static.example.com"},
		TLSMode:    TLSNamecheap,
		StaticRoot: "/srv/sites/static.example.com",
		CreatedAt:  time.Date(2026, 8, 27, 12, 0, 0, 0, time.UTC),
	}
	got, err := GenerateSiteBlock(s)
	if err != nil {
		t.Fatalf("GenerateSiteBlock: %v", err)
	}
	want := `# Generated by Portcullis. Do not edit manually.
# Service ID: site-beta
# Domains: static.example.com

static.example.com {
  import namecheap_tls
  root * /srv/sites/static.example.com
  file_server
}
`
	if got != want {
		t.Errorf("static block mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestGenerateIsDeterministic(t *testing.T) {
	a, err := GenerateSiteBlock(proxyService())
	if err != nil {
		t.Fatalf("first generate: %v", err)
	}
	b, err := GenerateSiteBlock(proxyService())
	if err != nil {
		t.Fatalf("second generate: %v", err)
	}
	if a != b {
		t.Error("generation is not deterministic for identical input")
	}
}

func TestGeneratedOutputContainsNoUnexpectedDirectives(t *testing.T) {
	got, err := GenerateSiteBlock(proxyService())
	if err != nil {
		t.Fatalf("GenerateSiteBlock: %v", err)
	}
	// The block must use the configured TLS import and a single
	// reverse_proxy line; nothing else may appear as a directive.
	if !strings.Contains(got, "import acme") {
		t.Error("expected TLS import line missing")
	}
	if n := strings.Count(got, "reverse_proxy"); n != 1 {
		t.Errorf("reverse_proxy appears %d times, want 1", n)
	}
	if strings.Contains(got, "file_server") {
		t.Error("proxy block must not contain file_server")
	}
}
